# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Sheffield NoDDSoc
site_url: https://noddsoc.co.uk
site_author: NoDDSoc
site_description: >-
  Welcome to the Not Only Dungeons and Dragons society website! Here, you'll find all the information you need about the society and how you can get involved.

# Repository information, shown in right side of navbar
repo_url: https://github.com/Sheffield-NoDDSoc/noddsoc.co.uk
repo_name: Sheffield-NoDDSoc/noddsoc.co.uk
edit_uri: edit/main/docs/

# Site navigation, contains all the pages users can view
nav: []

# Plugins and extensions used
plugins:
  - search # Site search
  # Git metadata
  - git-authors
  - git-committers:
      repository: Sheffield-NoDDSoc/noddsoc.co.uk
      branch: main
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  # External resources are downloaded during build
  - privacy
  # RSS feed for blog posts
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - blog:
      blog_dir: blog
  - glightbox: # Image zoom
      background: none
      shadow: false

# Extensions for markdown on pages
markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - tables
  - def_list
  - abbr
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      auto_append:
        - includes/definitions.md
        - includes/links.md
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Additional JavaScript
extra_javascript:
  # Used for Mathjax plugin
  - assets/js/mathjax.js
  # Allows sorting tables by a column
  - assets/js/tablesort.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: material
  favicon: assets/favicon.jpg
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
    - tags
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: teal

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: yellow
      accent: yellow

  # Updating the icons used for certain actions
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/git-alt
    annotation: material/information
    logo: material/star-four-points-circle-outline

extra:
  # Social media links on footer
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AmSsDjzkz3
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/noddsoc/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/NoDDSoc/
    - icon: fontawesome/brands/tumblr
      link: https://www.tumblr.com/noddsoc

  consent:
    title: Cookies
    actions:
      - accept
      - reject
      - manage
    description: >-
      This website uses cookies to anonymously track visits and interactions to this site, as well as feedback users give on each of the pages here so we know which pages need improvement. <b>This site does not track personal or identifiable information, ever.</b>

# Copyright notice, shown in footer
copyright: >
  Copyright &copy; 2025 Sheffield NoDDSoc <br />
  <a href="#__consent"><u>Manage cookies</u></a>

watch:
  - includes