# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Sheffield NoDDSoc
site_url: https://noddsoc.co.uk
site_author: NoDDSoc
site_description: >-
  Welcome to the Not Only Dungeons and Dragons society website! Here, you'll find all the information you need about the society and how you can get involved.

# Site navigation, contains all the pages users can view
nav:
  - Knowledge Base:
      - Welcome: index.md
      - Committee:
          - What We Do: committee/introduction.md
          - Who We Are: committee/members.md
          - Joining Committee: committee/join.md
      - Games:
          - Playing a Game: games/playing_a_game.md
          - Running a Game: games/running_a_game.md
      - Safety & Inclusivity:
          - Code of Conduct: safety/code_of_conduct.md
          - Triggers & Squicks: safety/triggers.md
      - Safety Tools:
          - Lines & Veils: safety/lines_veils.md
          - Card System: safety/cards.md
          - Script Changes: safety/script_changes.md

  - Newsletter:
      - newsletter/index.md

  - Library: https://sites.google.com/sheffield.ac.uk/noddsoclibrary

# Plugins and extensions used
plugins:
  - search # Site search
  # Git metadata
  - git-authors:
      enabled: false
  - git-committers:
      enabled: false
      repository: Sheffield-NoDDSoc/noddsoc.co.uk
      branch: main
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  # External resources are downloaded during build
  - privacy
  # RSS feed for newsletter posts
  - rss:
      match_path: newsletter/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - blog:
      blog_dir: newsletter
      blog_toc: true
      archive_toc: true
  - glightbox: # Image zoom
      background: none
      shadow: false
  - tags
  - meta

# Extensions for markdown on pages
markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - tables
  - def_list
  - abbr
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      auto_append:
        - includes/definitions.md
        - includes/links.md
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

# Additional JavaScript
extra_javascript:
  # Used for Mathjax plugin
  - assets/js/mathjax.js
  # Allows sorting tables by a column
  - assets/js/tablesort.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/css/button.css
  - assets/css/books.css

theme:
  name: material
  favicon: assets/favicon.jpg
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
#    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
    - tags
    - announce.dismiss

  palette:
    - scheme: slate
      primary: amber
      accent: orange

  # Updating the icons used for certain actions
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/git-alt
    annotation: material/information
    logo: noddsoc/logo

extra:
  # Social media links on footer
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/AmSsDjzkz3
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/noddsoc/
    - icon: fontawesome/brands/github
      link: https://github.com/Sheffield-NoDDSoc/noddsoc.co.uk

# Copyright notice, shown in footer
copyright: >
  Copyright &copy; 2025 Sheffield NoDDSoc <br />
  <a href="#__consent"><u>Manage cookies</u></a>

watch:
  - includes
  - overrides